apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      timeout: 30
      httpMethod: POST
      derivedFields: []
    version: 1
    editable: true
    limits_config:
      allow_structured_metadata: true

  - name: Prometheus
    type: prometheus
    uid: Prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    editable: true